// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4qomFnVRuJrmezg88a2eHuQGhJlGxduw',
    appId: '1:856422199421:web:dd15464358a104ea328114',
    messagingSenderId: '856422199421',
    projectId: 'pmferdian-35cb5',
    authDomain: 'pmferdian-35cb5.firebaseapp.com',
    storageBucket: 'pmferdian-35cb5.firebasestorage.app',
    measurementId: 'G-Y142362MZJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7zFuBizOd67GeLh0sid0rsxPslkXdZbI',
    appId: '1:856422199421:android:fbf4fb05738b8431328114',
    messagingSenderId: '856422199421',
    projectId: 'pmferdian-35cb5',
    storageBucket: 'pmferdian-35cb5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBM5AYE4-VE65IAH0AV0pQDHJEwhO95G3I',
    appId: '1:856422199421:ios:5b55563fda40b450328114',
    messagingSenderId: '856422199421',
    projectId: 'pmferdian-35cb5',
    storageBucket: 'pmferdian-35cb5.firebasestorage.app',
    iosBundleId: 'com.example.pahawang',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBM5AYE4-VE65IAH0AV0pQDHJEwhO95G3I',
    appId: '1:856422199421:ios:5b55563fda40b450328114',
    messagingSenderId: '856422199421',
    projectId: 'pmferdian-35cb5',
    storageBucket: 'pmferdian-35cb5.firebasestorage.app',
    iosBundleId: 'com.example.pahawang',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB4qomFnVRuJrmezg88a2eHuQGhJlGxduw',
    appId: '1:856422199421:web:f878bfe023358997328114',
    messagingSenderId: '856422199421',
    projectId: 'pmferdian-35cb5',
    authDomain: 'pmferdian-35cb5.firebaseapp.com',
    storageBucket: 'pmferdian-35cb5.firebasestorage.app',
    measurementId: 'G-D0994G8BB2',
  );
}
